print("-----------------------------------------Letter Macker-----------------------------------------")

date = input("Enter The Date--> ")
name = input("Enter Your Name--> ")
address = input("Enter Your Address--> ")
country = input("Enter Your Country--> ")
sub = input("Enter Your Subject--> ")
contant = input("Enter Your Contant--> ")
print("                                                                 ")
print("                                                                 ")
print("                                                                 ")

print(date)
print(name)
print(address)
print(country)
print(sub)
print("-------------------------------------------------")
print("Dear Sir")
print(contant)
print("                                                                 ")
print("                                                                 ")
print("Your Obediently")
print(name)
